import test from 'node:test';
import assert from 'node:assert/strict';
import {ViewerState,pageGeometry} from '../dist/viewer-state.mjs';
import {SplitState} from '../dist/split-state.mjs';
import {groupRepairErrors} from '../dist/engine.mjs';
import {groupErrorsForMarkers,simpleErrorMessage} from '../dist/error-markers.mjs';

test('viewer rotation normalizes clockwise, counter-clockwise and 180 degree operations',()=>{const v=new ViewerState();assert.equal(v.rotate(90),90);assert.equal(v.rotate(-90),0);assert.equal(v.rotate(180),180);assert.equal(v.rotate(180),0);});
test('viewer zoom works while rotated and snapshot restores page, scale and rotation',()=>{const v=new ViewerState({page:6,rotation:90,scale:1.2,fitMode:false});v.zoom(1.25);assert.equal(v.scale,1.5);const restored=new ViewerState(v.snapshot());assert.deepEqual(restored.snapshot(),{page:6,rotation:90,scale:1.5,fitMode:false});});
test('viewer fit accounts for swapped width and height at 90 degrees',()=>{const v=new ViewerState({rotation:90});v.fit(1000,600,800,1200,0);assert.equal(v.scale,600/800);const g=pageGeometry(800,1200,v);assert.equal(g.stageWidth,900);assert.equal(g.stageHeight,600);assert.equal(g.imageWidth,600);assert.equal(g.imageHeight,900);});
test('viewer page change preserves zoom and rotation',()=>{const v=new ViewerState({rotation:270,scale:2,fitMode:false});v.setPage(4);assert.deepEqual(v.snapshot(),{page:4,rotation:270,scale:2,fitMode:false});});
test('split pane clamps pointer and keyboard sizes to usable range',()=>{const s=new SplitState(60);assert.equal(s.fromPointer(5,100),30);assert.equal(s.fromPointer(95,100),75);assert.equal(s.nudge(-2),73);assert.equal(new SplitState(0).value,60);});
test('duplicate internal errors with the same repair scope are counted once',()=>{const base={type:'잘못된 연결',deviceIds:['A'],terminalIds:['A.1','B.1'],wireIds:['W1'],wrong:'x',correct:'y'},duplicate={...base,id:'internal-second',deviceIds:['B']};const grouped=groupRepairErrors([{...base,id:'first'},duplicate]);assert.equal(grouped.length,1);assert.deepEqual(grouped[0].deviceIds,['A','B']);});
test('different physical work on one wire remains separate errors',()=>{const shared={deviceIds:['A'],terminalIds:['A.1'],wireIds:['W1'],wrong:'x',correct:'y'};assert.equal(groupRepairErrors([{...shared,id:'color',type:'전선 색상'},{...shared,id:'crimp',type:'압착단자 규격'}]).length,2);});
test('multiple terminal faults on one terminal block create one counted marker',()=>{const problem={terminalMap:{'TB1.1':{deviceId:'TB1',displayNumber:'1'},'TB1.2':{deviceId:'TB1',displayNumber:'2'}}},base={deviceIds:['TB1'],wireIds:['W1'],wrong:'잘못',correct:'수정'};const groups=groupErrorsForMarkers(problem,[{...base,id:'a',type:'압착단자 규격',terminalIds:['TB1.1']},{...base,id:'b',type:'절연튜브',terminalIds:['TB1.2']}],[]);assert.equal(groups.length,1);assert.equal(groups[0].count,2);assert.equal(groups[0].anchorDeviceId,'TB1');});
test('missing connection explanation avoids internal NET terminology',()=>{const problem={terminalMap:{'A.1':{deviceId:'A',displayNumber:'1'},'B.2':{deviceId:'B',displayNumber:'2'}}},message=simpleErrorMessage(problem,{type:'필수 연결 누락',terminalIds:['A.1','B.2']},[]);assert.match(message,/A 1.*B 2/);assert.doesNotMatch(message,/NET/i);});
test('missing connection explanation uses a compact repair pair without internal terms',()=>{const problem={terminalMap:{'TB4.T1':{deviceId:'TB4',displayNumber:'T1'},'INVERTER.U':{deviceId:'INVERTER',displayNumber:'U'}}},message=simpleErrorMessage(problem,{type:'필수 연결 누락',terminalIds:['TB4.T1','INVERTER.U'],correct:'TB4.T1 ↔ INVERTER.U 또는 같은 NET 내 동등한 JUMP 연결이 필요합니다.'},[]);assert.equal(message,'TB4 T1 → INVERTER U 연결 X');assert.doesNotMatch(message,/NET/i);});
